name: GuardDuty
version: ${project.version}
main: me.blok.guard.Guard
depend: [PlaceholderAPI]
description: Guard Duty plugin for Mr_Lonely
commands:
  offduty:
    description: Go off duty
  onduty:
    description: Go on duty
  duty:
    description: View Guard commands